services:
    web:
        build: ./web
        volumes:
            - ./web:/app
            - node_modules_web:/app/node_modules
        restart: unless-stopped
        env_file:
            - .env
        command: npm run ${NODE_ENV}
        ports:
            - 80:80
volumes:
    node_modules_web:
